"""Tests for Telegram HTML formatting (channels/telegram.py pure functions)."""

pytest = __import__("pytest")
telegram_mod = pytest.importorskip("palmtop.channels.telegram")

from palmtop.channels.telegram import md_to_telegram_html, prepare_telegram_message, sanitize_telegram_html


class TestMdToTelegramHtml:
    def test_bold(self):
        assert "<b>bold</b>" in md_to_telegram_html("**bold**")

    def test_italic_star(self):
        assert "<i>italic</i>" in md_to_telegram_html("*italic*")

    def test_italic_underscore(self):
        assert "<i>italic</i>" in md_to_telegram_html("_italic_")

    def test_inline_code(self):
        result = md_to_telegram_html("`code here`")
        assert "<code>code here</code>" in result

    def test_code_fence(self):
        result = md_to_telegram_html("```python\nprint('hi')\n```")
        assert "<pre>" in result
        assert "print(&#x27;hi&#x27;)" in result or "print('hi')" in result

    def test_link(self):
        result = md_to_telegram_html("[click](https://example.com)")
        assert '<a href="https://example.com">click</a>' in result

    def test_bare_url(self):
        result = md_to_telegram_html("Visit https://example.com for details")
        assert 'href="https://example.com"' in result

    def test_header_becomes_bold(self):
        result = md_to_telegram_html("## My Header")
        assert "<b>My Header</b>" in result

    def test_bullet_points(self):
        result = md_to_telegram_html("- item one\n- item two")
        assert "▸" in result

    def test_numbered_list(self):
        result = md_to_telegram_html("1. first\n2. second")
        assert "①" in result
        assert "②" in result

    def test_empty_string(self):
        assert md_to_telegram_html("") == ""

    def test_html_escaping(self):
        result = md_to_telegram_html("use x < y & z > w")
        assert "&lt;" in result
        assert "&amp;" in result
        assert "&gt;" in result


class TestSanitizeTelegramHtml:
    def test_removes_unsupported_tags(self):
        result = sanitize_telegram_html("<div>hello</div>")
        assert "<div>" not in result
        assert "hello" in result

    def test_keeps_supported_tags(self):
        result = sanitize_telegram_html("<b>bold</b>")
        assert "<b>bold</b>" in result

    def test_closes_unclosed_tags(self):
        result = sanitize_telegram_html("<b>unclosed")
        assert "</b>" in result

    def test_empty_string(self):
        assert sanitize_telegram_html("") == ""


class TestPrepareTelegramMessage:
    def test_full_pipeline(self):
        """Pipeline should convert markdown and sanitize."""
        result = prepare_telegram_message("**bold** and `code`")
        assert "<b>bold</b>" in result
        assert "<code>code</code>" in result

    def test_strips_bad_html_from_md(self):
        """Unsupported tags generated by edge cases should be stripped."""
        result = prepare_telegram_message("normal text")
        assert "<div>" not in result
